# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_account', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=256)),
                ('user_create_date', models.DateTimeField()),
                ('user_gender', models.NullBooleanField(default=None)),
                ('user_image', models.ImageField(upload_to='user_images')),
                ('user_school', models.CharField(max_length=100)),
                ('user_deparment', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_autobiography', models.CharField(max_length=500)),
                ('user_type', models.CharField(max_length=20)),
                ('is_temp_user', models.BooleanField(default=True)),
                ('is_admin_user', models.BooleanField(default=False)),
            ],
        ),
    ]
