#-*- coding:utf-8 -*-
from courses.models import *
CourseAdminstrator.objects.all().delete()

CourseAdminstrator.objects.create(admin_id='AC', admin_name='工程技術研究所自動化及控制學程')
CourseAdminstrator.objects.create(admin_id='AD', admin_name='建築系')
CourseAdminstrator.objects.create(admin_id='AT', admin_name='應用科技學士學位學程')
CourseAdminstrator.objects.create(admin_id='BA', admin_name='企業管理系')
CourseAdminstrator.objects.create(admin_id='BB', admin_name='醫學工程學士學位學程')
CourseAdminstrator.objects.create(admin_id='BE', admin_name='醫學工程研究所')
CourseAdminstrator.objects.create(admin_id='CC', admin_name='人文課程')
CourseAdminstrator.objects.create(admin_id='CD', admin_name='創意設計學士班')
CourseAdminstrator.objects.create(admin_id='CE', admin_name='工程學士班')
CourseAdminstrator.objects.create(admin_id='CH', admin_name='化學工程系')
CourseAdminstrator.objects.create(admin_id='CI', admin_name='色彩與照明科技研究所')
CourseAdminstrator.objects.create(admin_id='CS', admin_name='資訊工程系')
CourseAdminstrator.objects.create(admin_id='CT', admin_name='營建工程系')
CourseAdminstrator.objects.create(admin_id='CX', admin_name='學士後色彩影像與照明科技學士學位學程')
CourseAdminstrator.objects.create(admin_id='DE', admin_name='設計研究所[99學年前]')
CourseAdminstrator.objects.create(admin_id='DT', admin_name='工商設計系')
CourseAdminstrator.objects.create(admin_id='DX', admin_name='學士後創意設計學士學位學程')
CourseAdminstrator.objects.create(admin_id='EC', admin_name='電資學士班')
CourseAdminstrator.objects.create(admin_id='EE', admin_name='電機工程系')
CourseAdminstrator.objects.create(admin_id='EN', admin_name='應用科技研究所')
CourseAdminstrator.objects.create(admin_id='EO', admin_name='光電工程研究所')
CourseAdminstrator.objects.create(admin_id='EP', admin_name='師資培育中心')
CourseAdminstrator.objects.create(admin_id='ET', admin_name='電子工程系')
CourseAdminstrator.objects.create(admin_id='FB', admin_name='財務金融學士學位學程')
CourseAdminstrator.objects.create(admin_id='FE', admin_name='教學資源中心&推廣教育中心')
CourseAdminstrator.objects.create(admin_id='FG', admin_name='全校外語選修課程(應用外語系)')
CourseAdminstrator.objects.create(admin_id='FL', admin_name='應用外語系')
CourseAdminstrator.objects.create(admin_id='FN', admin_name='財務金融研究所')
CourseAdminstrator.objects.create(admin_id='GE', admin_name='通識課程')
CourseAdminstrator.objects.create(admin_id='GX', admin_name='學士後綠能產業機電工程學士學位學程')
CourseAdminstrator.objects.create(admin_id='HC', admin_name='不分系學士班')
CourseAdminstrator.objects.create(admin_id='IB', admin_name='智慧財產權學士學位學程')
CourseAdminstrator.objects.create(admin_id='IM', admin_name='工業管理系')
CourseAdminstrator.objects.create(admin_id='MA', admin_name='MBA')
CourseAdminstrator.objects.create(admin_id='MB', admin_name='管理學士班')
CourseAdminstrator.objects.create(admin_id='ME', admin_name='機械工程系')
CourseAdminstrator.objects.create(admin_id='MG', admin_name='管理研究所')
CourseAdminstrator.objects.create(admin_id='MI', admin_name='資訊管理系')
CourseAdminstrator.objects.create(admin_id='MS', admin_name='材料科技研究所')
CourseAdminstrator.objects.create(admin_id='PA', admin_name='專利研究所')
CourseAdminstrator.objects.create(admin_id='SA', admin_name='學務處服務型通識課程')
CourseAdminstrator.objects.create(admin_id='TB', admin_name='科技管理學士學位學程')
CourseAdminstrator.objects.create(admin_id='TM', admin_name='科技管理研究所')
CourseAdminstrator.objects.create(admin_id='TX', admin_name='材料科學與工程系')
CourseAdminstrator.objects.create(admin_id='VE', admin_name='數位學習與教育研究所');

###################
CourseInformation.objects.all().delete()

CourseInformation.objects.create(course_administrator=CourseAdminstrator.objects.get(admin_name='教學資源中心&推廣教育中心'), course_name='科技英文', course_teacher='李奎皓', course_type=1, course_discription='Focus is on the following topics:<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧Brief history of how the English Language became the language of science.<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧Latin and Greek word elements, their usage and meaning.<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧Expansion of scientific vocabulary, and their usage and meaning.<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧The correct use of scientific terminology .<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧The correct use of English in describing math, numbers and quantities.<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧The correct use of verb tense and prepositions for scientific communication..<br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;‧Using active voice in speaking, and passive voice in writing technical documents.', course_website='http://info.ntust.edu.tw/faith/edua/app/qry_linkoutline.aspx?semester=1062&courseno=FE1621701')
CourseInformation.objects.create(course_administrator=CourseAdminstrator.objects.get(admin_name='資訊管理系'), course_name='物件導向程式語言', course_teacher='林伯慎', course_type=0, course_discription='介紹物件導向程式語言的概念和更高級的設計問題。 一些Java示範程式碼將在課堂上進行介紹和說明。 （需要Java編程語言的基礎知識。）\r<br>\r<br>Introduce the concepts of object-oriented programming language and more advanced design issues. A few Java sample codes will be presented and illustrated in the class. (Basic knowledge of Java programming language is required.)', course_website='http://info.ntust.edu.tw/faith/edua/app/qry_linkoutline.aspx?semester=1062&courseno=MI4204302')
CourseInformation.objects.create(course_administrator=CourseAdminstrator.objects.get(admin_name='人文課程'), course_name='表達與經典閱讀（一）', course_teacher='王慧燕', course_type=0, course_discription='1、課程教材的安排\n<br>  （1）抒發情思之古今文學作品的導讀與賞析。\n<br>  （2）中華文化歷代哲人對生命學習的探問與討論。\n<br>\n<br>2、授課的核心關懷\n<br>  （1）實感與時義：從經典汲取有益於探索生命的資糧，學習以己身之生活經驗為基礎，用生活化的眼光來解讀經典，並賦予經典時代意義。\n<br>  （2）視域與格局：以關懷他者（人文社會、自然環境、其他生命……）為出發點，培養己他互為主體的胸懷，開擴心量、拓展生命內涵，為人生引路。\n<br>\n<br>3、課程主題的擬訂\n<br>   ---以古典經籍為源，以現代篇章之議題為流。\n<br>   如：（1）以探討「立志」、「志道」、「志於學」的經典文句為序說，展開關於「我決定……」的價值性思考。\n<br>  （2）以探問「求放心」的經籍為據，思考關於「收心操」之方法性的議題。', course_website='http://info.ntust.edu.tw/faith/edua/app/qry_linkoutline.aspx?semester=1051&courseno=CC1246301')

print(CourseInformation.objects.all())