# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdminstrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20)),
                ('admin_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfile', models.FileField(upload_to='static/files/courses/')),
                ('cfile_class', models.CharField(max_length=20)),
                ('cfile_year', models.CharField(max_length=4)),
                ('cfile_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_teacher', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=20)),
                ('course_discription', models.CharField(max_length=500, null=True)),
                ('course_website', models.CharField(max_length=100, null=True)),
                ('course_administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseAdminstrator')),
            ],
        ),
        migrations.AddField(
            model_name='coursefile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInformation'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.CourseFile'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
