# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefile',
            options={'ordering': ['cfile_year', 'cfile_content'], 'permissions': (('can_look', '查看檔案'), ('can_upload', '上傳檔案'))},
        ),
    ]
